create table appointment (
    created_at timestamp(6) not null,
    date timestamp(6) not null,
    id bigint generated by default as identity,
    id_diagnosis bigint unique,
    id_doctor bigint,
    id_mastery bigint,
    id_patient bigint not null,
    id_recipe bigint unique,
    last_updated timestamp(6),
    status varchar(255) not null check (status in ('ASSIGNED','IN_PROGRESS','FINISHED')),
    primary key (id)
);

create table diagnosis (
    id bigint generated by default as identity,
    observations varchar(255) not null,
    primary key (id)
);

create table diagnosis_vital_sign (
    id_diagnosis bigint not null,
    id_vital_sign bigint not null
);

create table doctor (
    id bigint not null,
    primary key (id)
);

create table doctor_mastery (
    id_doctor bigint not null,
    id_mastery bigint not null
);

create table invoice (
    subtotal float(53) not null,
    total float(53) not null,
    appointment_id bigint not null unique,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    code varchar(255),
    primary key (id)
);

create table mastery (
    price float(53) not null,
    id bigint generated by default as identity,
    code varchar(255) not null,
    description varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table medical_supply (
    price numeric(38,2) not null,
    id bigint generated by default as identity,
    description varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table profile (
    id bigint generated by default as identity,
    user_id bigint unique,
    primary key (id)
);

create table recipe (
    id bigint generated by default as identity,
    primary key (id)
);

create table recipe_medical_supply (
    id_medical_supply bigint not null,
    id_recipe bigint not null
);

create table "user" (
    status boolean,
    created_at timestamp(6),
    id bigint generated by default as identity,
    last_updated timestamp(6),
    profile_id bigint unique,
    email varchar(255) not null unique,
    name varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null check (role in ('ADMIN','DOCTOR','NURSE','ACCOUNTING_MANAGER','PATIENT')),
    surname varchar(255) not null,
    primary key (id)
);

create table vital_sign (
    cough boolean not null,
    fatigue boolean not null,
    fever boolean not null,
    headache boolean not null,
    sore_throat boolean not null,
    temperature float(53) not null,
    id bigint generated by default as identity,
    primary key (id)
);
